const baseCustomers = [
  ['Linh', 'Nguyen', 'linh.nguyen@example.com', 'Ho Chi Minh City'],
  ['Minh', 'Tran', 'minh.tran@example.com', 'Hanoi'],
  ['An', 'Pham', 'an.pham@example.com', 'Da Nang'],
  ['Mai', 'Le', 'mai.le@example.com', 'Hue'],
  ['Khoa', 'Vo', 'khoa.vo@example.com', 'Can Tho'],
  ['Thao', 'Dang', 'thao.dang@example.com', 'Nha Trang'],
  ['Duy', 'Bui', 'duy.bui@example.com', 'Hoi An'],
  ['Nhi', 'Hoang', 'nhi.hoang@example.com', 'Da Lat'],
  ['Bao', 'Do', 'bao.do@example.com', 'Hai Phong'],
  ['Vy', 'Phan', 'vy.phan@example.com', 'Vung Tau'],
  ['Tuan', 'Ngo', 'tuan.ngo@example.com', 'Quy Nhon'],
  ['Lan', 'Huynh', 'lan.huynh@example.com', 'Bien Hoa'],
  ['Nam', 'Ly', 'nam.ly@example.com', 'Buon Ma Thuot'],
  ['Ha', 'Truong', 'ha.truong@example.com', 'Phan Thiet'],
  ['Quang', 'Mai', 'quang.mai@example.com', 'Long Xuyen'],
  ['Trang', 'Cao', 'trang.cao@example.com', 'Rach Gia'],
  ['Hieu', 'Lam', 'hieu.lam@example.com', 'Thai Nguyen'],
  ['My', 'Vu', 'my.vu@example.com', 'Bac Ninh'],
  ['Son', 'Dinh', 'son.dinh@example.com', 'Thanh Hoa'],
  ['Yen', 'Ta', 'yen.ta@example.com', 'Vinh'],
  ['Phuc', 'Ha', 'phuc.ha@example.com', 'Pleiku'],
  ['Giang', 'Duong', 'giang.duong@example.com', 'Tuy Hoa'],
  ['Long', 'Dang', 'long.dang@example.com', 'Sa Dec'],
  ['Oanh', 'Pham', 'oanh.pham@example.com', 'My Tho'],
  ['Dat', 'Vo', 'dat.vo@example.com', 'Tra Vinh'],
  ['Hanh', 'Bui', 'hanh.bui@example.com', 'Soc Trang'],
  ['Tin', 'Le', 'tin.le@example.com', 'Bac Lieu'],
  ['Chi', 'Ho', 'chi.ho@example.com', 'Ca Mau'],
  ['Phuong', 'Nguyen', 'phuong.nguyen@example.com', 'Kon Tum'],
  ['Lam', 'Tran', 'lam.tran@example.com', 'Dong Hoi'],
];

export const customerPassword = 'customer123';

export const customers = baseCustomers.map(([firstName, lastName, email, city], index) => ({
  firstName,
  lastName,
  email,
  role: 'user',
  newsletter: index % 3 !== 0,
  addresses: [
    {
      label: 'Home',
      firstName,
      lastName,
      address1: `${24 + index} Le Loi Street`,
      city,
      postalCode: `70${String(200 + index).padStart(3, '0')}`,
      country: 'Vietnam',
      phone: `091${String(2000000 + index * 846).slice(0, 7)}`,
    },
  ],
  lastLoginAt: index % 4 === 0 ? null : new Date(Date.now() - index * 24 * 60 * 60 * 1000),
}));
