export const professionalPage = {
  pageId: 'professionals',
  eyebrow: 'Trade & Contract',
  title: 'Designed for Professionals',
  subtitle:
    'Dedicated resources for architects, interior designers, stylists, retailers, and contract teams working on refined residential and hospitality spaces.',
  heroImage:
    'https://images.unsplash.com/photo-1751945965380-017e4ac16506?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600',
  cards: [
    {
      title: 'Trade Account',
      description: 'Request access to trade pricing, project ordering, invoices, and account support.',
      linkLabel: 'Apply',
      href: '#inquiry',
      order: 1,
      isActive: true,
    },
    {
      title: 'Image Bank',
      description: 'Download approved lifestyle imagery, product cutouts, mood assets, and press-ready files.',
      linkLabel: 'Request Access',
      href: '#inquiry',
      order: 2,
      isActive: true,
    },
    {
      title: 'Showrooms',
      description: 'Book appointments for material reviews, project presentations, and product walkthroughs.',
      linkLabel: 'Book Visit',
      href: '#inquiry',
      order: 3,
      isActive: true,
    },
    {
      title: 'Catalogues',
      description: 'Browse collection catalogues, contract lookbooks, and finish guides for project planning.',
      linkLabel: 'View Files',
      href: '#catalogues',
      order: 4,
      isActive: true,
    },
    {
      title: 'Contract Projects',
      description: 'Coordinate FF&E selections for hospitality, workspace, retail, and residential developments.',
      linkLabel: 'Start Project',
      href: '#inquiry',
      order: 5,
      isActive: true,
    },
    {
      title: 'Press & Company',
      description: 'Find company information, brand notes, sustainability references, and press contacts.',
      linkLabel: 'Contact',
      href: '#inquiry',
      order: 6,
      isActive: true,
    },
  ],
  inquiryTitle: 'Contract Project Inquiry',
  inquiryIntro:
    'Share a few details about your project and our professional team will follow up with relevant resources, pricing, and next steps.',
  cataloguesTitle: 'Latest Professional Files',
  catalogues: [
    {
      title: 'BREW Contract Lookbook 2026',
      fileSize: '12 MB',
      fileUrl: '/downloads/brew-contract-lookbook.pdf',
      description: 'Hospitality, workspace, and residential project references.',
      order: 1,
      isActive: true,
    },
    {
      title: 'Materials and Finish Guide',
      fileSize: '8 MB',
      fileUrl: '/downloads/brew-materials-guide.pdf',
      description: 'Wood, textile, metal, ceramic, and care references.',
      order: 2,
      isActive: true,
    },
    {
      title: 'Trade Price Overview',
      fileSize: '5 MB',
      fileUrl: '/downloads/brew-trade-overview.pdf',
      description: 'Demo pricing structure and order workflow for trade users.',
      order: 3,
      isActive: true,
    },
  ],
  servicesTitle: 'Professional Services',
  services: [
    'Trade pricing and project quotes',
    'Material and finish guidance',
    'Product imagery and specification files',
    'Contract ordering support',
    'Showroom appointments and remote presentations',
    'Styling support for residential and hospitality spaces',
  ],
  isPublished: true,
};
